apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::006808541377:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-7AQCZ6CEUF5E
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::006808541377:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-26T07:47:58Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2153"
  uid: ec7bbf4e-6407-48b1-ba3a-22a6523bbc55
